### ISSUE TITLE
Multiple Projects Support

### ISSUE THREAD

**Issue by MoElaSec** [realstoman/vuejs-tailwindcss-portfolio#23]
How would I be able to route each project to its own page that describes it instead of all the projects when I click on any of them will send me to the same page coded here: {{ SingleProject.vue }}

**Comment by realstoman** [comment]
Thank you @MoElaSec for opening this issue.

There are multiple ways you can do dynamic routing for projects and posts. I kept this project simple to cover essential features of Vue.js.

Here are some resources you can add dynamic routing for posts and projects:
- https://router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route
- https://codesource.io/dynamic-routing-in-vuejs-explained-with-an-example/
- https://dev.to/samzhangjy/creating-a-personal-blog-with-vue-js-part-1-getting-started-36nl

Let me know if this solves your problem so I can close this issue.

**Comment by MoElaSec** [comment]
Thanks a lot...😀
